// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Modules.Inventory.Infrastructure.Persistence;

#nullable disable

namespace Wms.Modules.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260813113708_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Allocated")
                        .HasColumnType("integer")
                        .HasColumnName("allocated");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_balance");

                    b.HasIndex("WarehouseId", "LocationId")
                        .HasDatabaseName("ix_inventory_balance_warehouse_id_location_id");

                    b.HasIndex("WarehouseId", "SkuId", "Status")
                        .HasDatabaseName("ix_inventory_balance_warehouse_id_sku_id_status");

                    b.HasIndex("SkuId", "WarehouseId", "LocationId", "Status")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_balance_sku_id_warehouse_id_location_id_status");

                    b.ToTable("inventory_balance", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_balance_allocated_non_negative", "allocated >= 0");

                            t.HasCheckConstraint("ck_inventory_balance_allocated_not_exceeds_quantity", "allocated <= quantity");

                            t.HasCheckConstraint("ck_inventory_balance_allocated_only_available", "status = 'AVAILABLE' OR allocated = 0");

                            t.HasCheckConstraint("ck_inventory_balance_quantity_non_negative", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocatedDelta")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_delta");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_delta");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_ledger");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_inventory_ledger_request_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_ledger_warehouse_id");

                    b.HasIndex("WarehouseId", "SkuId")
                        .HasDatabaseName("ix_inventory_ledger_warehouse_id_sku_id");

                    b.ToTable("inventory_ledger", "inventory");
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("requested_quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_reservation");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_reservation_request_id");

                    b.HasIndex("WarehouseId", "SkuId")
                        .HasDatabaseName("ix_inventory_reservation_warehouse_id_sku_id");

                    b.ToTable("inventory_reservation", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservation_requested_positive", "requested_quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.ReservationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_reservation_line");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_inventory_reservation_line_location_id");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_inventory_reservation_line_reservation_id");

                    b.ToTable("inventory_reservation_line", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservation_line_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Infrastructure.Persistence.InventoryOperation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation_type");

                    b.HasKey("RequestId")
                        .HasName("pk_inventory_operation");

                    b.ToTable("inventory_operation", "inventory");
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.ReservationLine", b =>
                {
                    b.HasOne("Wms.Modules.Inventory.Domain.InventoryReservation", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_reservation_line_inventory_reservation_reservatio");
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryReservation", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
