// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Modules.Inventory.Infrastructure.Persistence;

#nullable disable

namespace Wms.Modules.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260813190000_AddLedgerReferenceColumns")]
    partial class AddLedgerReferenceColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.Accuracy.CycleCounting.CycleCountResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CountedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("counted_at");

                    b.Property<string>("CountedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("counted_by");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("counted_quantity");

                    b.Property<Guid>("CycleCountTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_count_task_id");

                    b.Property<int>("ExpectedAllocated")
                        .HasColumnType("integer")
                        .HasColumnName("expected_allocated");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<string>("ExpectedStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("expected_status");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("outcome");

                    b.Property<int>("Variance")
                        .HasColumnType("integer")
                        .HasColumnName("variance");

                    b.HasKey("Id")
                        .HasName("pk_cycle_count_result");

                    b.HasIndex("CycleCountTaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_cycle_count_result_cycle_count_task_id");

                    b.ToTable("cycle_count_result", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_cycle_count_result_counted_non_negative", "counted_quantity >= 0");

                            t.HasCheckConstraint("ck_cycle_count_result_expected_non_negative", "expected_quantity >= 0 AND expected_allocated >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.Accuracy.CycleCounting.CycleCountTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("due_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("evidence");

                    b.Property<int?>("ExpectedAllocated")
                        .HasColumnType("integer")
                        .HasColumnName("expected_allocated");

                    b.Property<int?>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<string>("ExpectedStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("expected_status");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<int>("RiskScoreAtCreation")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score_at_creation");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_cycle_count_task");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cycle_count_task_created_at");

                    b.HasIndex("SkuId", "WarehouseId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_cycle_count_task_sku_id_warehouse_id_location_id")
                        .HasFilter("status IN ('PENDING','INPROGRESS')");

                    b.HasIndex("WarehouseId", "Status", "Priority")
                        .HasDatabaseName("ix_cycle_count_task_warehouse_id_status_priority");

                    b.ToTable("cycle_count_task", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_cycle_count_task_expected_non_negative", "expected_quantity >= 0 AND expected_allocated >= 0");

                            t.HasCheckConstraint("ck_cycle_count_task_risk_score_non_negative", "risk_score_at_creation >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.Accuracy.InventoryAccuracySignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocatedAtSignal")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_at_signal");

                    b.Property<int>("AvailableAtSignal")
                        .HasColumnType("integer")
                        .HasColumnName("available_at_signal");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("signal_type");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<Guid?>("SourceReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_reference_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source_type");

                    b.Property<string>("StatusAtSignal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status_at_signal");

                    b.Property<int>("SystemQuantityAtSignal")
                        .HasColumnType("integer")
                        .HasColumnName("system_quantity_at_signal");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_accuracy_signal");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_inventory_accuracy_signal_occurred_at");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_accuracy_signal_request_id");

                    b.HasIndex("SkuId", "LocationId")
                        .HasDatabaseName("ix_inventory_accuracy_signal_sku_id_location_id");

                    b.HasIndex("WarehouseId", "SignalType")
                        .HasDatabaseName("ix_inventory_accuracy_signal_warehouse_id_signal_type");

                    b.ToTable("inventory_accuracy_signal", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_accuracy_signal_allocated_non_negative", "allocated_at_signal >= 0");

                            t.HasCheckConstraint("ck_inventory_accuracy_signal_available_non_negative", "available_at_signal >= 0");

                            t.HasCheckConstraint("ck_inventory_accuracy_signal_system_quantity_non_negative", "system_quantity_at_signal >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.Accuracy.Reconciliation.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_delta");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResolutionNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_adjustment");

                    b.HasIndex("ReconciliationId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_adjustment_reconciliation_id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_adjustment_request_id");

                    b.HasIndex("WarehouseId", "SkuId")
                        .HasDatabaseName("ix_inventory_adjustment_warehouse_id_sku_id");

                    b.ToTable("inventory_adjustment", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_adjustment_delta_nonzero", "quantity_delta <> 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.Accuracy.Reconciliation.InventoryReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("counted_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CycleCountResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_count_result_id");

                    b.Property<Guid>("CycleCountTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_count_task_id");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<bool>("IsLargeVariance")
                        .HasColumnType("boolean")
                        .HasColumnName("is_large_variance");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reconciliation_status");

                    b.Property<string>("ResolutionNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Variance")
                        .HasColumnType("integer")
                        .HasColumnName("variance");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_reconciliation");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_inventory_reconciliation_created_at");

                    b.HasIndex("CycleCountResultId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_reconciliation_cycle_count_result_id");

                    b.HasIndex("WarehouseId", "ReconciliationStatus")
                        .HasDatabaseName("ix_inventory_reconciliation_warehouse_id_reconciliation_status");

                    b.HasIndex("WarehouseId", "LocationId", "SkuId")
                        .HasDatabaseName("ix_inventory_reconciliation_warehouse_id_location_id_sku_id");

                    b.ToTable("inventory_reconciliation", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reconciliation_quantities_non_negative", "expected_quantity >= 0 AND counted_quantity >= 0");

                            t.HasCheckConstraint("ck_inventory_reconciliation_variance_nonzero", "variance <> 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.Accuracy.Scanning.ScanMovementEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_location_id");

                    b.Property<string>("DestinationScanValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("destination_scan_value");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operator_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("SkuScanValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku_scan_value");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<string>("SourceScanValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_scan_value");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_scan_movement_evidence");

                    b.HasIndex("MovementId")
                        .IsUnique()
                        .HasDatabaseName("ix_scan_movement_evidence_movement_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_scan_movement_evidence_occurred_at");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_scan_movement_evidence_request_id");

                    b.HasIndex("WarehouseId", "SkuId")
                        .HasDatabaseName("ix_scan_movement_evidence_warehouse_id_sku_id");

                    b.ToTable("scan_movement_evidence", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_scan_movement_evidence_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Allocated")
                        .HasColumnType("integer")
                        .HasColumnName("allocated");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_balance");

                    b.HasIndex("WarehouseId", "LocationId")
                        .HasDatabaseName("ix_inventory_balance_warehouse_id_location_id");

                    b.HasIndex("WarehouseId", "SkuId", "Status")
                        .HasDatabaseName("ix_inventory_balance_warehouse_id_sku_id_status");

                    b.HasIndex("SkuId", "WarehouseId", "LocationId", "Status")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_balance_sku_id_warehouse_id_location_id_status");

                    b.ToTable("inventory_balance", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_balance_allocated_non_negative", "allocated >= 0");

                            t.HasCheckConstraint("ck_inventory_balance_allocated_not_exceeds_quantity", "allocated <= quantity");

                            t.HasCheckConstraint("ck_inventory_balance_allocated_only_available", "status = 'AVAILABLE' OR allocated = 0");

                            t.HasCheckConstraint("ck_inventory_balance_quantity_non_negative", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocatedDelta")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_delta");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid?>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_delta");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_ledger");

                    b.HasIndex("MovementId")
                        .HasDatabaseName("ix_inventory_ledger_movement_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_inventory_ledger_request_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_ledger_warehouse_id");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_inventory_ledger_reference_type_reference_id");

                    b.HasIndex("WarehouseId", "SkuId")
                        .HasDatabaseName("ix_inventory_ledger_warehouse_id_sku_id");

                    b.ToTable("inventory_ledger", "inventory");
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_location_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<string>("StatusFrom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status_from");

                    b.Property<string>("StatusTo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status_to");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movement");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_movement_request_id");

                    b.HasIndex("WarehouseId", "SkuId")
                        .HasDatabaseName("ix_inventory_movement_warehouse_id_sku_id");

                    b.ToTable("inventory_movement", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movement_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("requested_quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_reservation");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_reservation_request_id");

                    b.HasIndex("WarehouseId", "SkuId")
                        .HasDatabaseName("ix_inventory_reservation_warehouse_id_sku_id");

                    b.ToTable("inventory_reservation", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservation_requested_positive", "requested_quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.ReservationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_reservation_line");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_inventory_reservation_line_location_id");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_inventory_reservation_line_reservation_id");

                    b.ToTable("inventory_reservation_line", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservation_line_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Infrastructure.Persistence.InventoryOperation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation_type");

                    b.HasKey("RequestId")
                        .HasName("pk_inventory_operation");

                    b.ToTable("inventory_operation", "inventory");
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.ReservationLine", b =>
                {
                    b.HasOne("Wms.Modules.Inventory.Domain.InventoryReservation", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_reservation_line_inventory_reservation_reservatio");
                });

            modelBuilder.Entity("Wms.Modules.Inventory.Domain.InventoryReservation", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
