// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Modules.Fulfillment.Infrastructure.Persistence;

#nullable disable

namespace Wms.Modules.Fulfillment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FulfillmentDbContext))]
    partial class FulfillmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fulfillment")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Modules.Fulfillment.Domain.SourcingDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("committed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_snapshot");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("SourcingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("sourcing_request_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fulfillment_sourcing_decision");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfillment_sourcing_decision_request_id");

                    b.HasIndex("SourcingRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfillment_sourcing_decision_sourcing_request_id");

                    b.ToTable("fulfillment_sourcing_decision", "fulfillment");
                });

            modelBuilder.Entity("Wms.Modules.Fulfillment.Domain.SourcingLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("SourcingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("sourcing_request_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fulfillment_sourcing_line");

                    b.HasIndex("SourcingRequestId")
                        .HasDatabaseName("ix_fulfillment_sourcing_line_sourcing_request_id");

                    b.HasIndex("SourcingRequestId", "SkuId")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfillment_sourcing_line_sourcing_request_id_sku_id");

                    b.ToTable("fulfillment_sourcing_line", "fulfillment", t =>
                        {
                            t.HasCheckConstraint("ck_fulfillment_sourcing_line_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Fulfillment.Domain.SourcingOrderLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_number");

                    b.Property<Guid>("OutboundOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbound_order_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_fulfillment_sourcing_order_link");

                    b.HasIndex("DecisionId")
                        .HasDatabaseName("ix_fulfillment_sourcing_order_link_decision_id");

                    b.HasIndex("OutboundOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfillment_sourcing_order_link_outbound_order_id");

                    b.ToTable("fulfillment_sourcing_order_link", "fulfillment");
                });

            modelBuilder.Entity("Wms.Modules.Fulfillment.Domain.SourcingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fulfillment_sourcing_request");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfillment_sourcing_request_request_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fulfillment_sourcing_request_status");

                    b.ToTable("fulfillment_sourcing_request", "fulfillment");
                });

            modelBuilder.Entity("Wms.Modules.Fulfillment.Domain.SourcingLine", b =>
                {
                    b.HasOne("Wms.Modules.Fulfillment.Domain.SourcingRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("SourcingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fulfillment_sourcing_line_sourcing_requests_sourcing_reques");
                });

            modelBuilder.Entity("Wms.Modules.Fulfillment.Domain.SourcingRequest", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
