// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Modules.Inbound.Infrastructure.Persistence;

#nullable disable

namespace Wms.Modules.Inbound.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InboundDbContext))]
    [Migration("20260814122026_AddOutbox")]
    partial class AddOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inbound")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Integration.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_message_created_at");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_event_id");

                    b.HasIndex("PublishedAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_message_published_at_next_attempt_at");

                    b.ToTable("outbox_message", "inbound");
                });

            modelBuilder.Entity("Wms.Modules.Inbound.Domain.InboundReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_reference");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt_number");

                    b.Property<DateTime?>("ReceivingStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("receiving_started_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inbound_receipt");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_receipt_receipt_number");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_receipt_request_id");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_inbound_receipt_warehouse_id_status");

                    b.ToTable("inbound_receipt", "inbound");
                });

            modelBuilder.Entity("Wms.Modules.Inbound.Domain.InboundReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Disposition")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("disposition");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("received_quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inbound_receipt_line");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_inbound_receipt_line_receipt_id");

                    b.HasIndex("ReceiptId", "SkuId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_receipt_line_receipt_id_sku_id");

                    b.ToTable("inbound_receipt_line", "inbound", t =>
                        {
                            t.HasCheckConstraint("ck_inbound_receipt_line_expected_non_negative", "expected_quantity >= 0");

                            t.HasCheckConstraint("ck_inbound_receipt_line_received_non_negative", "received_quantity >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inbound.Domain.PutawayTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("inventory_status");

                    b.Property<Guid?>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<Guid>("ReceiptLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_line_id");

                    b.Property<Guid>("ReceiveRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("receive_record_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inbound_putaway_task");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_inbound_putaway_task_created_at");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_inbound_putaway_task_receipt_id");

                    b.HasIndex("ReceiveRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_putaway_task_receive_record_id");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_inbound_putaway_task_warehouse_id_status");

                    b.ToTable("inbound_putaway_task", "inbound", t =>
                        {
                            t.HasCheckConstraint("ck_inbound_putaway_task_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inbound.Domain.ReceiptLineReceiveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("disposition");

                    b.Property<Guid>("InventoryOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_operation_id");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("inventory_status");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_line_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ReceivingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiving_location_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id")
                        .HasName("pk_inbound_receipt_record");

                    b.HasIndex("InventoryOperationId")
                        .HasDatabaseName("ix_inbound_receipt_record_inventory_operation_id");

                    b.HasIndex("ReceiptLineId")
                        .HasDatabaseName("ix_inbound_receipt_record_receipt_line_id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_receipt_record_request_id");

                    b.ToTable("inbound_receipt_record", "inbound", t =>
                        {
                            t.HasCheckConstraint("ck_inbound_receipt_record_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Inbound.Domain.InboundReceiptLine", b =>
                {
                    b.HasOne("Wms.Modules.Inbound.Domain.InboundReceipt", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inbound_receipt_line_inbound_receipt_receipt_id");
                });

            modelBuilder.Entity("Wms.Modules.Inbound.Domain.InboundReceipt", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
