// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Modules.MasterData.Infrastructure.Persistence;

#nullable disable

namespace Wms.Modules.MasterData.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MasterDataDbContext))]
    [Migration("20260813105925_InitialMasterData")]
    partial class InitialMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("master_data")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brand");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_brand_name");

                    b.ToTable("brand", "master_data");
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_category_name");

                    b.ToTable("category", "master_data");
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_product_name");

                    b.ToTable("product", "master_data");
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("height_cm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("LengthCm")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("length_cm");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uuid")
                        .HasColumnName("uom_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("weight_kg");

                    b.Property<decimal?>("WidthCm")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("width_cm");

                    b.HasKey("Id")
                        .HasName("pk_sku");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_code");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sku_product_id");

                    b.HasIndex("UomId")
                        .HasDatabaseName("ix_sku_uom_id");

                    b.ToTable("sku", "master_data", t =>
                        {
                            t.HasCheckConstraint("ck_sku_measurements_non_negative", "weight_kg >= 0 AND length_cm >= 0 AND width_cm >= 0 AND height_cm >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.SkuBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_sku_barcode");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("ix_sku_barcode_sku_id");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_barcode_value");

                    b.ToTable("sku_barcode", "master_data");
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.Uom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_uom");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_uom_code");

                    b.ToTable("uom", "master_data");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "EA",
                            Name = "Each"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "BOX",
                            Name = "Box"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "PCS",
                            Name = "Piece"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "KG",
                            Name = "Kilogram"
                        });
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.Sku", b =>
                {
                    b.HasOne("Wms.Modules.MasterData.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sku_product_product_id");

                    b.HasOne("Wms.Modules.MasterData.Domain.Uom", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sku_uoms_uom_id");

                    b.Navigation("Product");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.SkuBarcode", b =>
                {
                    b.HasOne("Wms.Modules.MasterData.Domain.Sku", null)
                        .WithMany("Barcodes")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sku_barcode_skus_sku_id");
                });

            modelBuilder.Entity("Wms.Modules.MasterData.Domain.Sku", b =>
                {
                    b.Navigation("Barcodes");
                });
#pragma warning restore 612, 618
        }
    }
}
