// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Modules.Transfers.Infrastructure.Persistence;

#nullable disable

namespace Wms.Modules.Transfers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransfersDbContext))]
    partial class TransfersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transfers")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Integration.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("consumer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_inbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_inbox_message_processed_at");

                    b.HasIndex("Consumer", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_message_consumer_event_id");

                    b.ToTable("inbox_message", "transfers");
                });

            modelBuilder.Entity("Wms.Modules.Transfers.Domain.TransferDiscrepancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("TransferLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_line_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_discrepancy");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_discrepancy_request_id");

                    b.HasIndex("TransferLineId")
                        .HasDatabaseName("ix_transfer_discrepancy_transfer_line_id");

                    b.ToTable("transfer_discrepancy", "transfers", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_discrepancy_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Transfers.Domain.TransferLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConfirmedVarianceQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_variance_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("InboundReceiptLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbound_receipt_line_id");

                    b.Property<Guid?>("OutboundOrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbound_order_line_id");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("received_quantity");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("requested_quantity");

                    b.Property<int>("ShippedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("shipped_quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("TransferOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_order_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transfer_line");

                    b.HasIndex("TransferOrderId")
                        .HasDatabaseName("ix_transfer_line_transfer_order_id");

                    b.HasIndex("TransferOrderId", "SkuId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_line_transfer_order_id_sku_id");

                    b.ToTable("transfer_line", "transfers", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_line_no_negative_intransit", "received_quantity + confirmed_variance_quantity <= shipped_quantity");

                            t.HasCheckConstraint("ck_transfer_line_received_non_negative", "received_quantity >= 0");

                            t.HasCheckConstraint("ck_transfer_line_requested_positive", "requested_quantity > 0");

                            t.HasCheckConstraint("ck_transfer_line_shipped_non_negative", "shipped_quantity >= 0");

                            t.HasCheckConstraint("ck_transfer_line_variance_non_negative", "confirmed_variance_quantity >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Transfers.Domain.TransferOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_warehouse_id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_reference");

                    b.Property<Guid?>("InboundReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbound_receipt_id");

                    b.Property<Guid?>("OutboundOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbound_order_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipped_at");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_warehouse_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("TransferNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transfer_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transfer_order");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_order_request_id");

                    b.HasIndex("TransferNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_order_transfer_number");

                    b.HasIndex("DestinationWarehouseId", "Status")
                        .HasDatabaseName("ix_transfer_order_destination_warehouse_id_status");

                    b.HasIndex("SourceWarehouseId", "Status")
                        .HasDatabaseName("ix_transfer_order_source_warehouse_id_status");

                    b.ToTable("transfer_order", "transfers", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_order_distinct_warehouses", "source_warehouse_id <> destination_warehouse_id");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Transfers.Domain.TransferReceiveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("inventory_status");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ReceivingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiving_location_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("TransferLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_line_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_receive_record");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_receive_record_request_id");

                    b.HasIndex("TransferLineId")
                        .HasDatabaseName("ix_transfer_receive_record_transfer_line_id");

                    b.ToTable("transfer_receive_record", "transfers", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_receive_record_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Transfers.Domain.TransferLine", b =>
                {
                    b.HasOne("Wms.Modules.Transfers.Domain.TransferOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("TransferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_line_transfer_orders_transfer_order_id");
                });

            modelBuilder.Entity("Wms.Modules.Transfers.Domain.TransferOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
