// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Modules.Outbound.Infrastructure.Persistence;

#nullable disable

namespace Wms.Modules.Outbound.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OutboundDbContext))]
    partial class OutboundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("outbound")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Integration.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_message_created_at");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_event_id");

                    b.HasIndex("PublishedAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_message_published_at_next_attempt_at");

                    b.ToTable("outbox_message", "outbound");
                });

            modelBuilder.Entity("Wms.Modules.Outbound.Domain.FulfillmentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AllocatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("allocated_at");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalOrderReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_order_reference");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_number");

                    b.Property<DateTime?>("PackedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("packed_at");

                    b.Property<DateTime?>("PickingStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("picking_started_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_outbound_fulfillment_order");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_fulfillment_order_order_number");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_fulfillment_order_request_id");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_outbound_fulfillment_order_warehouse_id_status");

                    b.ToTable("outbound_fulfillment_order", "outbound");
                });

            modelBuilder.Entity("Wms.Modules.Outbound.Domain.FulfillmentOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("requested_quantity");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbound_fulfillment_order_line");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_outbound_fulfillment_order_line_order_id");

                    b.HasIndex("OrderId", "SkuId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_fulfillment_order_line_order_id_sku_id");

                    b.ToTable("outbound_fulfillment_order_line", "outbound", t =>
                        {
                            t.HasCheckConstraint("ck_outbound_fulfillment_order_line_quantity_positive", "requested_quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Outbound.Domain.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PackageNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("package_number");

                    b.Property<DateTime>("PackedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("packed_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbound_package");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_package_order_id");

                    b.HasIndex("PackageNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_package_package_number");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_package_request_id");

                    b.ToTable("outbound_package", "outbound");
                });

            modelBuilder.Entity("Wms.Modules.Outbound.Domain.PickTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<int>("PickedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("picked_quantity");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("required_quantity");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("ReservationLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_line_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_outbound_pick_task");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbound_pick_task_created_at");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_outbound_pick_task_order_id");

                    b.HasIndex("ReservationLineId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_pick_task_reservation_line_id");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_outbound_pick_task_warehouse_id_status");

                    b.ToTable("outbound_pick_task", "outbound", t =>
                        {
                            t.HasCheckConstraint("ck_outbound_pick_task_picked_non_negative", "picked_quantity >= 0");

                            t.HasCheckConstraint("ck_outbound_pick_task_picked_not_exceeds_required", "picked_quantity <= required_quantity");

                            t.HasCheckConstraint("ck_outbound_pick_task_required_positive", "required_quantity > 0");
                        });
                });

            modelBuilder.Entity("Wms.Modules.Outbound.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CarrierCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("carrier_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("shipment_number");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbound_shipment");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_shipment_order_id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_shipment_request_id");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_shipment_shipment_number");

                    b.ToTable("outbound_shipment", "outbound");
                });

            modelBuilder.Entity("Wms.Modules.Outbound.Domain.FulfillmentOrderLine", b =>
                {
                    b.HasOne("Wms.Modules.Outbound.Domain.FulfillmentOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbound_fulfillment_order_line_outbound_fulfillment_order_");
                });

            modelBuilder.Entity("Wms.Modules.Outbound.Domain.FulfillmentOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
